
import React, {useEffect} from "react";
import {tw_col_center} from "../../../system_code/tw/tw_tools";
import {GlobalsContext} from "../../../system_state/context_globals/globals_context";
import {process_API_KEY, process_API_URL, process_EMAIL_FROM, process_EMAIL_TO, process_URL_ROOT_APP} from "./api_keys";

import {Button} from "@mui/material";
import {useHistory} from "react-router";
import {tw_divider_vertical} from "../../../system_code/tw/tw_components";

const EntranceSuccess = (props0:any) => {

    const { global_props, global_dispatch } = React.useContext(GlobalsContext);

    const history = useHistory();

    const init_state={
        send_email_after_google:false,
    }

    const [state, set_state] = React.useState({...init_state});

    const in_state = (name:string, data:any) => {

        set_state({
            ...state,
            ...{
                [name]: data,
            }
        })

    }


    useEffect(() => {

        console.log('=== global_props.entrance_step ',global_props.entrance_step)
            if ("sign_in_mode_with_google" === global_props.entrance_step) {

                console.log('=== global_props.entrance_step do email !!! ')
                if(!state.send_email_after_google) {
                    in_state('send_email_after_google', true)
                }
            }

        setTimeout(function () {
            history.push(`/user_space`)
        }, 5000);

        return () => {

        };
    }, [global_props.entrance_step]);

    let tMessage = `
        <div style="margin: 20px auto;">
 
            <a style="font-style: italic; font-weight: 600">This e-mail Message is automaticaly generated by: www.xx.com </a>
            <br>
            <a>from the ${process_URL_ROOT_APP}</a>
            <br>
            <a style="font-style: normal; font-weight: 600">To confirm your email</a>
            <a href=${
                    process_URL_ROOT_APP
                    // +"/signup?url_email="+this.props.input_email_value
                    // +"&url_id="+this.props.user_token
            } 
                style="font-style: normal; font-weight: 600"
                id="link_to_press1"
                >press on this link
            </a>

        </div>`;

    let tSignature = `
        <div style="margin: 20px auto;">

            <a>This is Signature </a>
            <div>
                <img src="https://services.google.com/fh/files/emails/g1logo-01.png" width="50px" >
            </div>

        </div>`;

     let tFooter = `
        <div style="margin: 20px auto;">

            <a>This is Footer </a>

        </div>`;

     tMessage = `tMessage`
     tSignature = `tSignature`
     tFooter = `tFooter1`

    return (

    <div className={tw_col_center}>
        <div>EntranceSuccess</div>

        {tw_divider_vertical()}

        <div>You are Successfuly Logged in !</div>

        {tw_divider_vertical()}
        {tw_divider_vertical()}

        <Button
            variant="contained"
                onClick={() => {
                    history.push(`/user_space`)
                }
            }>
            Continue
        </Button>

        {/*{(!state.send_email_after_google)?<></>:*/}
        {/*    <SendEmail*/}
        {/*        p_url ={process_API_URL}*/}
        {/*        p_api_key ={process_API_KEY}*/}
        {/*        p_email_from ={"☁️The LifeStyle Cloud ☁️"+' <'+process_EMAIL_FROM+'>'}*/}
        {/*        p_email_to ={process_EMAIL_TO}*/}

        {/*        // p_email_to ={global_props.current_user.email}*/}

        {/*        p_subject ={'Sign In'}*/}
        {/*        p_message ={tMessage}*/}
        {/*        p_signature ={tSignature}*/}
        {/*        p_footer ={tFooter}*/}
        {/*        p_call_back={()=>{*/}
        {/*            console.log('=== finish of SendEmail ')*/}
        {/*            in_state('send_email_after_google',false)*/}
        {/*        }}*/}
        {/*    />*/}
        {/*}*/}

        {/*<UserDashboard />*/}
    </div>

);
};

export default EntranceSuccess
